// <auto-generated />
using System;
using FarmBuddy.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmBuddy.Repository.Migrations
{
    [DbContext(typeof(FarmBuddyDbContext))]
    [Migration("20251122161714_AddJwtConfig")]
    partial class AddJwtConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmBuddy.Common.Entities.BackendAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()")
                        .HasComment("建立時間");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("顯示名稱");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("是否啟用");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2")
                        .HasComment("最後登入時間");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("密碼雜湊值");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("使用者名稱");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_BackendAccount_Username");

                    b.ToTable("BackendAccounts", null, t =>
                        {
                            t.HasComment("後端帳戶");
                        });
                });

            modelBuilder.Entity("FarmBuddy.Common.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聊天內容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("建立時間 (用於排序)");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasComment("角色：User (用戶) 或 Assistant (AI)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("用戶ID (對應 Line UserId)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChatMessage_UserId");

                    b.ToTable("ChatMessages", null, t =>
                        {
                            t.HasComment("聊天紀錄");
                        });
                });

            modelBuilder.Entity("FarmBuddy.Common.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("配置描述");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("配置键");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("配置值");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting", t =>
                        {
                            t.HasComment("系统配置");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Endpoint:CwaApi",
                            Value = "https://opendata.cwa.gov.tw/api"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Endpoint:CwaApiKey",
                            Value = "氣象開放資料平台會員授權碼"
                        },
                        new
                        {
                            Id = 3,
                            Key = "OpenAIOption:ChatModelId",
                            Value = "gpt-4"
                        },
                        new
                        {
                            Id = 4,
                            Key = "OpenAIOption:ApiKey",
                            Value = "YOUR_API_KEY"
                        },
                        new
                        {
                            Id = 5,
                            Key = "GeminiOption:ChatModelId",
                            Value = "gemini-2.5-flash"
                        },
                        new
                        {
                            Id = 6,
                            Key = "GeminiOption:ApiKey",
                            Value = "YOUR_API_KEY"
                        },
                        new
                        {
                            Id = 7,
                            Description = "AI類型: 0=OpenAI, 1=Gemini",
                            Key = "KernelConfig:AiModelType",
                            Value = "0"
                        },
                        new
                        {
                            Id = 8,
                            Key = "LineConfig:ChannelId",
                            Value = "YOUR_CHANNEL_ID"
                        },
                        new
                        {
                            Id = 9,
                            Key = "LineConfig:ChannelSecret",
                            Value = "YOUR_CHANNEL_SECRET"
                        },
                        new
                        {
                            Id = 10,
                            Description = "系統提示詞",
                            Key = "KernelConfig:SystemMessage",
                            Value = "YOUR_SystemMessage"
                        },
                        new
                        {
                            Id = 11,
                            Description = "助手提示詞",
                            Key = "KernelConfig:AssistantMessage",
                            Value = "YOUR_AssistantMessage"
                        },
                        new
                        {
                            Id = 12,
                            Description = "JWT頒發者",
                            Key = "JwtConfig:Issuer",
                            Value = "farm-buddy-api"
                        },
                        new
                        {
                            Id = 13,
                            Description = "JWT客戶端",
                            Key = "JwtConfig:Audience",
                            Value = "farm-buddy-api"
                        },
                        new
                        {
                            Id = 14,
                            Description = "JWT密鑰",
                            Key = "JwtConfig:Key",
                            Value = "u5w/8x+A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
