// <auto-generated />
using FarmBuddy.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmBuddy.Repository.Migrations
{
    [DbContext(typeof(FarmBuddyDbContext))]
    partial class FarmBuddyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmBuddy.Common.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("配置描述");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("配置键");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("配置值");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting", t =>
                        {
                            t.HasComment("系统配置");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Endpoint:CwaApi",
                            Value = "https://opendata.cwa.gov.tw/api"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Endpoint:CwaApiKey",
                            Value = "氣象開放資料平台會員授權碼"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
